name: Generate Version Report

on:
  schedule:
    - cron: '0 0 * * *'  # Run every day at midnight
  workflow_dispatch:

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate version report
        run: python scripts/generate_version_report.py

      - name: Check for changes
        id: git_status
        run: |
          if git diff --quiet -- docs_health_report.md; then
            echo "No changes to report."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Version report has changed."
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request with changes
        if: steps.git_status.outputs.changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          BRANCH_NAME="docs/version-report-update-${{ github.run_id }}"
          git checkout -b $BRANCH_NAME
          git add docs_health_report.md
          git commit -m "docs: Update version report"
          git push origin $BRANCH_NAME
          gh pr create \
            --base "main" \
            --head "$BRANCH_NAME" \
            --title "Docs: Update Version Report (${{ github.run_id }})" \
            --body "Automated documentation version report update. Please review and merge."